BT2_EG=$(BT2_HOME)/example

output_tssim2_reads_u.fastq: .unp_tssim2.sam .paired_tssim2.sam
	../qsim-parse-input f -- $^ -- $(BT2_EG)/reference/lambda_virus.fa -- output_tssim2

.paired_tssim2.sam: output_tssim_reads_c_1.fastq
	$(BT2_HOME)/bowtie2 -x $(BT2_EG)/index/lambda_virus \
                        -1 output_tssim_reads_c_1.fastq -1 output_tssim_reads_d_1.fastq \
                        -2 output_tssim_reads_c_2.fastq -2 output_tssim_reads_d_2.fastq \
                        -S $@ \
                        --mapq-extra

.unp_tssim2.sam: output_tssim_reads_u.fastq output_tssim_reads_b.fastq
	$(BT2_HOME)/bowtie2 -x $(BT2_EG)/index/lambda_virus \
                        -U output_tssim_reads_u.fastq -U output_tssim_reads_b.fastq \
                        -S $@ \
                        --mapq-extra

output_tssim_reads_u.fastq output_tssim_reads_b.fastq output_tssim_reads_c_1.fastq: .unp_tssim.sam .paired_tssim.sam
	../qsim-parse-input ifs -- $^ -- $(BT2_EG)/reference/lambda_virus.fa -- output_tssim

../qsim-parse-input:
	$(MAKE) -C ..

.unp_tssim.sam:
	$(BT2_HOME)/bowtie2 -x $(BT2_EG)/index/lambda_virus \
                        -U lambda_mason_unp.fastq \
                        -S $@ \
                        --mapq-extra

.paired_tssim.sam:
	$(BT2_HOME)/bowtie2 -x $(BT2_EG)/index/lambda_virus \
                        -1 lambda_mason_paired_1.fastq \
                        -2 lambda_mason_paired_2.fastq \
                        -S $@ \
                        --mapq-extra

.PHONY: clean
clean:
	rm -f .*_tssim*.sam output_tssim*
