BT2_EG=$(BT2_HOME)/example

output.txt: .unp_e2e.sam .paired_e2e.sam
	../qsim-parse-input ifs -- $^ -- $(BT2_EG)/reference/lambda_virus.fa -- output_e2e

../qsim-parse-input:
	$(MAKE) -C ..

.unp_e2e.sam:
	$(BT2_HOME)/bowtie2 -x $(BT2_EG)/index/lambda_virus \
                            -U $(BT2_EG)/reads/longreads.fq \
                            -S $@ \
			    --mapq-extra

.paired_e2e.sam:
	$(BT2_HOME)/bowtie2 -x $(BT2_EG)/index/lambda_virus \
                            -1 $(BT2_EG)/reads/reads_1.fq \
                            -2 $(BT2_EG)/reads/reads_2.fq \
                            -S $@ \
			    --mapq-extra

.PHONY: clean
clean:
	rm -f .*_e2e.sam output_e2e*
