BT2_EG=$(BT2_HOME)/example

output.txt: .unp_tssim.sam .paired_tssim.sam
	../qsim-parse-input ifs -- $^ -- $(BT2_EG)/reference/lambda_virus.fa -- output_tssim

../qsim-parse-input:
	$(MAKE) -C ..

.unp_tssim.sam:
	$(BT2_HOME)/bowtie2 -x $(BT2_EG)/index/lambda_virus \
                        -U lambda_mason_unp.fastq \
                        -S $@ \
                        --mapq-extra

.paired_tssim.sam:
	$(BT2_HOME)/bowtie2 -x $(BT2_EG)/index/lambda_virus \
                        -1 lambda_mason_paired_1.fastq \
                        -2 lambda_mason_paired_2.fastq \
                        -S $@ \
                        --mapq-extra

.PHONY: clean
clean:
	rm -f .*_tssim.sam output_tssim*
