language: c++
compiler:
  - clang
  - gcc
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - conda config --add channels r
  - conda config --add channels bioconda
install:
  - conda install --yes numpy scipy panda scikit-learn
script:
  - make -C src
  - make -C src/test
